// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs



Table otps {
  email varchar [primary key]
  otp varchar(6) [primary key]
  created_at timestamptz [not null, default: `now()`]
}

Table tokens {
  token varchar [primary key]
  role varchar [not null]
  created_at timestamptz [not null, default: `now()`]
}

Table boards {
  id int [primary key]
  name varchar [not null]
  description varchar [not null]
}

Table posts {
  id varchar [primary key]
  title varchar [not null]
  upvotes int [not null, default: 0]
  downvotes int [not null, default: 0]
  body text [note: 'Content of the post', not null]
  board int [ref: < boards.id, not null]
  moderation_status varchar [not null, default: 'pending']
  created_at timestamptz [not null, default: `now()`]
}

Table comments {
  id int [primary key]
  post_id varchar [not null, ref: < posts.id, note: 'The post this comment belongs to']
  parent_id int [ref: < comments.id, note: 'Parent comment ID for nested comments']
  body text [not null, note: 'Content of the comment']
  upvotes int [not null, default: 0]
  downvotes int [not null, default: 0]
  created_at timestamptz [not null, default: `now()`]
}

